const constants = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    RESET_MARKERS: 'RESET_MARKERS',
    ADD_MARKER: 'ADD_MARKER',
    REVOKE_MARKER: 'REVOKE_MARKER',
    EDIT_MARKER: 'EDIT_MARKER',
    REMOVE_MARKER: 'REMOVE_MARKER',
    UPDATE_MARKER_FAV: 'UPDATE_MARKER_FAV',
    RESET_EVENTTYPES: 'RESET_EVENTTYPES',
    RESET_MAPPINS: 'RESET_MAPPINS',
    UPDATE_MARKER_STATUS: 'UPDATE_MARKER_STATUS',
    RESET_SCHEDULES: 'RESET_SCHEDULES',
    ADD_SCHEDULE: 'ADD_SCHEDULE',
    EDIT_SCHEDULE: 'EDIT_SCHEDULE',
    REMOVE_SCHEDULE: 'REMOVE_SCHEDULE',
    UPDATE_SCHEDULES_STATUS: 'UPDATE_SCHEDULES_STATUS',
    UPDATE_MARKERS_STATUS: 'UPDATE_MARKERS_STATUS',
    RESET_HOME: 'RESET_HOME',
    
}

export default constants