const constants = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    RESET_MARKERS: 'RESET_MARKERS',
    ADD_MARKER: 'ADD_MARKER',
    UPDATE_MARKER_FAV: 'UPDATE_MARKER_FAV',
    RESET_EVENTTYPES: 'RESET_EVENTTYPES',
    RESET_MAPPINS: 'RESET_MAPPINS',
    UPDATE_MARKER_STATUS: 'UPDATE_MARKER_STATUS',
    RESET_SCHEDULES: 'RESET_SCHEDULES',
    ADD_SCHEDULE: 'ADD_SCHEDULE',
    UPDATE_SCHEDULES_STATUS: 'UPDATE_SCHEDULES_STATUS',
    UPDATE_MARKERS_STATUS: 'UPDATE_MARKERS_STATUS',
}

export default constants