const constants = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    RESET_MARKERS: 'RESET_MARKERS',
    ADD_MARKER: 'ADD_MARKER',
    UPDATE_MARKER_FAV: 'UPDATE_MARKER_FAV',
    RESET_EVENTTYPES: 'RESET_EVENTTYPES',
    RESET_MAPPINS: 'RESET_MAPPINS',
    RESET_SCHEDULES: 'RESET_SCHEDULES',
    ADD_SCHEDULE: 'ADD_SCHEDULE',
}

export default constants